title: Time software
description: A simple voice for a simple people

theme: just-the-docs

url: https://juckey13.github.io/time-software/

logo: "TM_.png"

aux_links:
  Support: https://t.me/hi_tarobot 
